### ISSUE TITLE
英文爛爛的初學者

### ISSUE THREAD

**Issue by MruHuang** [104corp/laravel-eloquent-generator#13]
希望能有中文版~
許願~windows使用終端機也能使用

**Comment by MilesChou** [comment]
事實上，我也是用破破的英文在寫這份文件，或許我寫份標準的中文版，再看來有沒有英文高手願意幫我轉英文好了XD

Windows 請另外開 issue 吧！

**Comment by MilesChou** [comment]
已寫好放在 wiki
https://github.com/104corp/laravel-eloquent-generator/wiki/%E4%B8%AD%E6%96%87
