### ISSUE TITLE
windows開發~與linux沒權限，矛盾大對決

### ISSUE THREAD

**Issue by MruHuang** [104corp/laravel-eloquent-generator#14]
小弟我開發laravel昰透過windows但是伺服昰使用linux(指會簡單指令)，目前有個問題想請教
由於linux昰內網，且權限鎖的很死(基本上我是windows開發完成clone過去),但是看到留言串有人使用windows尚未成功,想說還是透過linux使用該套件，在套件上看起來,應該是需要把eloquent-generator.phar放制於/usr/local/bin(小弟沒有權限動這裡)如果是這樣，請問有其他辦法安裝嗎?還是小弟我要去跪系統管理者了?

**Comment by MilesChou** [comment]
放 `/usr/local/bin` 只是選項（optional），不是必要項（required）

取代的做法一：把 .phar 放到你專案目錄下，再執行下面指令也行

```
php eloquent-generator.phar
```

取代的做法二：把 .phar 放到你可以控制的目錄，比方說 `/home/miles/.bin/` 接著設定 PATH 全域變數

```
export PATH=/home/miles/.bin/:$PATH
mv eloquent-generator.phar /home/miles/.bin/eloquent-generator
eloquent-generator
```

如果只有一個 Laravel 專案的話，用第一種做法應該是夠用的；如果有很多專案的話，再來考慮第二種做法也行

**Comment by MilesChou** [comment]
另外要注意的是， Linux 上裝的 PHP 版本，與套件是否足夠，可以執行下面兩個指令確認：

```
php -v
php -m
```

請參考 Laravel [官方文件](https://laravel.com/docs/5.4/installation#server-requirements)確認有哪些套件是要準備好的

**注意：這是必要的檢查項**，如果環境沒有準備好，那執行就極有可能會失敗

**Comment by MruHuang** [comment]
目前使用windows出現幾個問題
1.我設制應該是有設定好，但是還是出現設定問題QAQ，username打死了也是一樣
2.sqlite這個配制不能拿掉,否則會出現找不到資料庫的錯誤  [PDOException]  could not find driver
配制如下:
'connections' => [
        'sqlite' => [
            'driver' => 'mysql',
            'database' => env('DB_DATABASE','progras'),
            'prefix' => '',
        ],
        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => 'root',
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
]

C:\xampp\htdocs\dbuse>php eloquent-generator.phar
PHP Notice:  Undefined variable: host in phar://C:/xampp/htdocs/dbuse/eloquent-generator.phar/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php on line 104

Notice: Undefined variable: host in phar://C:/xampp/htdocs/dbuse/eloquent-generator.phar/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php on line 104

[PDOException]
  SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'progras'


eloquent-generator [--env ENV] [--config-file CONFIG-FILE] [--connection CONNECTION] [--output-dir OUTPUT-DIR] [--namespace NAMESPACE] [--overwrite] [--progress]

**Comment by MilesChou** [comment]
先正面回答這個錯誤：因為第一個 DB sqlite 的 driver ，你可能打錯了，要打 sqlite ， database 的值可能也要改一下。

```
'sqlite' => [
    'driver' => 'sqlite',
    'database' => 'some/dbfile.db',
    'prefix' => '',
],
```

但聽起來真正設定的「只有」 `mysql` DB ，你可以加參數 `--connection` 試試指定 db `mysql` ，這樣可以避免指令去掃其他 db 造成找不到 `driver` 的錯誤。

**Comment by MruHuang** [comment]
真的是我設定問題，但是我測了一下，感覺sqlite還是會去啟用配制為成後進入下一關了
抱歉一直詢問，接下來的問題我就看不懂了
'sqlite' => [
			'driver'   => 'sqlite',
			'database' => storage_path().'/progras.sqlite',
			'prefix'   => '',
		],

        'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],
]
[Noodlehaus\Exception\ParseException]
  PHP file threw an exception

  [ReflectionException]
  Class path.storage does not exist

**Comment by MilesChou** [comment]
這可能是個 bug ，因為在 return 設定 array 的時候，它需要去執行 `storage_path()` 得到結果，才能知道完整路徑。

但我指令並沒有寫如何解析 `storage_path()` 囧...

這問題有點難，你先試看看把 sqlite 區塊移除能不能正常運作好了XD

Related #15

**Comment by MruHuang** [comment]
我剛剛爬文好像是php7的問題，
我改成database_path()為路徑後
問題變為:
PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Container\Container::databasePath()

而再移除sqlite後
 [PDOException]
  could not find driver
找不到了QAQ

**Comment by MilesChou** [comment]
我猜你可能沒有裝 PDO driver ，可以下 `php -m` 查看看是不是有下面這兩個 driver ：

```
PDO
pdo_mysql
```

**Comment by MilesChou** [comment]
至於剛剛提到的錯誤：

```
PHP Fatal error: Uncaught Error: Call to undefined method Illuminate\Container\Container::databasePath()
```

這是 #15 要解決的問題

**Comment by MruHuang** [comment]
以解決~~~QAQ
會產生build的資料匣沒錯吧?
先回答上面安裝問題 PDO與pdo_mysql我是有安裝的還是會could not find driver(但是我發現問題的根源)
我發現在database.php理面每個資料庫的連結設定好像都會吃
connections指定資料庫並不會啟用效果(我先前指定mysql)
所以我沒有將sqlite、pgsql、sqlsrv等相關設定標記時，好像會因為這些資料庫設定不完整，導致 [PDOException]  could not find driver
所以解法就是將欲連線資料庫以外的設定檔，全部標記起來，在執行就成功了(QAQ灑花)

**Comment by MilesChou** [comment]
原來還有 `pgsql` 和 `sqlsrv` ，總之，成功就好XD

**Comment by MruHuang** [comment]
建制新的laravel專案database.php理面本來就會壅有各式預設資料檔XD
本來以為connections設定mysql應該就不會吃了，所以沒有特別覺得會是問題
結果，好像是不看connections直街跑全部的設定XD
PS.資料表有"**_**"(底線)的資料表命名好像會把"_"(底線)移除

**Comment by MilesChou** [comment]
補充說明： Model 名稱是這樣來的

https://github.com/104corp/laravel-eloquent-generator/blob/74ea363bba11e9790045383df3a70096ab708777/src/Generators/CodeGenerator.php#L68

用了 `Str::studly()` 來轉換 table 名稱
